### ISSUE TITLE
The default namespace should be removed from the app

### ISSUE THREAD

**Issue by redekok** [mondaine-esdl/etm-esdl#7]
The default namespace seems to be a duplicate of the EnergySystem one and is therefore redundant I think. Let's remove it (if you agree @noracato?).

![image](https://user-images.githubusercontent.com/5946498/99941950-2a589400-2d6f-11eb-8fd9-aaab83106b85.png)

**Comment by noracato** [comment]
Agreed, etmodel comminicates with the 'EnergySytem' extension as well (as seen in the [sample config](https://github.com/quintel/etmodel/blob/53eb6f9c0f22d423f69eb5f5e25f0e447ee33f99/config/config.sample.yml#L20)). We can safely remove the namespace.

**Comment by noracato** [comment]
No longer relevant
